### ISSUE TITLE
Update Material Icon set

### ISSUE THREAD

**Issue by lewismarsden-xft** [gl0b3/materialicons#3]
Hi, found this repo when looking for ways of using Material Icons in Vaadin. We're stuck on Vaadin 23 at the moment due to Jakarta migration issues, but have recently been using this through the Vaadin add-on directory and found it great so far.

I've noticed that there are newer Material Icons on the Google fonts site, but often icons I would like to use aren't present in this add-on. How do you generate/update your materialicons.js to get the list of icons? I'm wondering if it's possible to get an updated list of icons either with our own workaround or via an update through this repo.

**Comment by gl0b3** [comment]
Thank you for the kind words!
This project is not recent, so I don't remember exactly how materialicons.js was put together. I don't know what the source of the SVG was, but maybe I collected the 24px SVGs from the google github materialicons-design repository and put them in a JS. These are not synchronized with Google's updates, so my collection may differ from the latest set of icons.
I can see how it is possible to release a fresh version. In the meantime, could you tell me which icons you're missing? Thanks!

**Comment by gl0b3** [comment]
The iconset has refreshed, now the materialicons.js contains 2170 icons compared with the previous 1800+ icons.
See: [https://github.com/gl0b3/materialicons/tree/2.1.0](https://github.com/gl0b3/materialicons/tree/2.1.0)
The Materialicons-flow 2.1.0 Vaadin addon will be released soon, but in the meantime you can take a look for the source:
[https://github.com/gl0b3/materialicons-flow/tree/2.1.0](https://github.com/gl0b3/materialicons-flow/tree/2.1.0)
The repository also has a Vaadin demo project: materialicons-flow-demo.

**Comment by gl0b3** [comment]
@lewismarsden-xft: the Material Icons v2.1.0 for Vaadin 23 has been released. [https://vaadin.com/directory/component/material-icons-for-vaadin-14/2.1.0](https://vaadin.com/directory/component/material-icons-for-vaadin-14/2.1.0)
